language: python
python:
  - "2.7"

jobs:
  include:
    - stage: build
      script: 'pip install -r requirements.txt && python -m unittest discover'

    - stage: deploy
      script: 'pip install shipa-ci && shipa-ci --app=josh --server=$SHIPASERVER --email=$SHIPAEMAIL --password=$SHIPAPASSWORD --verbose'
